language: ruby
cache:
  - bundler
  - yarn
services:
  - postgresql
before_install:
  - gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
  - nvm install --lts
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle install --jobs=3 --retry=3
  - yarn
  - bin/rails db:create
  - bin/rails db:schema:load
script:
  - bundle exec rubocop
  - bundle exec rails test -vd
  - bundle exec rails test:system -v
