language: ruby
cache:
  - bundler
  - yarn
services:
  - postgresql
before_install:
  - nvm install --lts
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle install --jobs=3 --retry=3
  - yarn
  - bin/rails db:create
  - bin/rails db:schema:load
script:
  - bundle exec rubocop
  - bundle exec rails test -vd
  - bundle exec rails test:system -v
