default: &default
  adapter: postgresql
  host: db
  username: postgres
  password: password

development:
  <<: *default
  database: closet_monster_dev
  port: 3333

test:
  <<: *default
  database: closet_monster_test
  port: 3333

production:
  <<: *default
  database: closet_monster_prod
