default: &default
  adapter: postgresql

development:
  <<: *default
  database: closet_monster_dev

test:
  <<: *default
  database: closet_monster_test

production:
  <<: *default
  database: closet_monster_prod
