development:
  adapter: postgresql
  database: closet_monster_dev

test:
  adapter: sqlite3
  database: db/test_db/closet_monster_test.sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

# production:
#   <<: *default
#   database: db/production.sqlite3
